// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruppEx.Data;

namespace TruppEx.Migrations
{
    [DbContext(typeof(TruppContext))]
    partial class TruppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TruppEx.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TruppEx.Models.LifeEvent", b =>
                {
                    b.Property<int>("LifeEventID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmployeeID");

                    b.Property<DateTime>("EventDate");

                    b.Property<int>("LifeEventTypeID");

                    b.HasKey("LifeEventID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("LifeEventTypeID");

                    b.ToTable("LifeEvents");
                });

            modelBuilder.Entity("TruppEx.Models.LifeEventType", b =>
                {
                    b.Property<int>("LifeEventTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("LifeEventTypeID");

                    b.ToTable("LifeEventTypes");
                });

            modelBuilder.Entity("TruppEx.Models.LifeEvent", b =>
                {
                    b.HasOne("TruppEx.Models.Employee", "Employee")
                        .WithMany("LifeEvents")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TruppEx.Models.LifeEventType", "LifeEventType")
                        .WithMany("LifeEvents")
                        .HasForeignKey("LifeEventTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
